import type { Metadata } from "next";
import { Geist, Geist_Mono, Playwrite_NO, Parisienne } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playwriteNO = Playwrite_NO({
  variable: "--font-playwrite-no",
  weight: ["100", "200", "300", "400"],
});

const parisienne = Parisienne({
  variable: "--font-parisienne",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playwriteNO.variable} ${parisienne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
